//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrphanageMVC
{
    using OrphanageMVC.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class reqTable
    {
        public int rId { get; set; }
        public string requirementName { get; set; }
        public string requirementStatus { get; set; }
        public int oId { get; set; }
    
        public virtual OrphanageRegistrationView orphanageRegistration1 { get; set; }
    }
}
